name: Local CI-CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build -t naveen266/devops-app:${{ github.run_number }} .
          docker push naveen266/devops-app:${{ github.run_number }}

      - name: Update Image Tag in Terraform
        run: |
          sed -i 's/devops-app:.*/devops-app:${{ github.run_number }}"/' infra/main.tf

      - name: Terraform Init
        run: cd infra && terraform init

      - name: Terraform Apply
        run: cd infra && terraform apply -auto-approve

      - name: Verify Deployment
        run: kubectl get pods
