name: Local CI-CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:

      # 1. Checkout source code
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Docker Login
      - name: Docker Login
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # 3. Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t naveen266/devops-app:${{ github.run_number }} .

      # 4. Push Docker Image
      - name: Push Docker Image
        run: |
          docker push naveen266/devops-app:${{ github.run_number }}

      # 5. Create/Update Kubernetes Deployment
      - name: Apply Kubernetes Manifest
        run: |
          kubectl apply -f K8S/deployment.yaml

      # 6. Update Kubernetes Image
      - name: Update Kubernetes Image
        run: |
          kubectl set image deployment/devops-app devops-app=naveen266/devops-app:${{ github.run_number }}

      # 7. Wait for Rollout
      - name: Wait for Deployment
        run: |
          kubectl rollout status deployment/devops-app --timeout=120s

      # 8. Verify Deployment
      - name: Verify Deployment
        run: |
          echo "===== Deployment ====="
          kubectl get deployment devops-app

          echo "===== Pods ====="
          kubectl get pods -o wide
